---
# Amazon Textract React example
files:
  - path: public/index.html
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/App.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/AwsFactory.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/Config.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/AddRemoveAssets.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/ExplorerCard.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/ExplorerTree.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/ExtractButtons.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/ImageDisplay.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/ImageLoader.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/index.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/LoginCard.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/setupTests.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/TextractModel.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/Utils.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/App.test.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/ExplorerCard.test.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/ExplorerTree.test.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/ExtractButtons.test.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/ImageDisplay.test.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/ImageLoader.test.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/LoginCard.test.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/TestData.js
    services:
      - cognito
      - s3
      - sqs
      - textract
  - path: src/__test__/TextractModel.test.js
    services:
      - cognito
      - s3
      - sqs
      - textract
...